### ISSUE TITLE
some advices && feature requests

### ISSUE THREAD

**Issue by siteshen** [brantou/emacs-go-tag#1]
coding style advices:
1. `(interactive "sTags:")` should be `(interactive "sTags: ")`

feature requests:
1. `go-tag-add` && `go-tag-remove` may provide default value `"json"`
2. function `go-tag-readd` is useful when field names change frequently, eg. when design struct

**Comment by brantou** [comment]
@siteshen Thanks for your feedback. I adopted the coding style advice and added the `go-tag-refresh` function.

Default value:
- `go-tag-add` default value `json`
- `go-tag-refresh` default value `json`
- `go-tag-remove` default value `all`(remove all field tags)

Have any questions, please feedback, I am happy to discuss.
